### ISSUE TITLE
Object pattern

### ISSUE THREAD

**Issue by PetarIvancevic** [kenspirit/joi-to-json#10]
Hey,

thx for building this package and alleviating a lot of headaches with joi->json conversions. I'm currently working on an documentation script that will be generated based on the joi validation we do. If possible could you add support for object patterns? For example lets say you have an object that has dynamic keys, but each of those keys are objects. 

Example JSON with dynamic keys: 
```javascript
{
  dynamicKeyHolder: {
    someKey: {
      id: 1,
      name: 'Jack'
    },
    someOtherKey: {
      id: 2,
      name: 'Jane'
    },
  }
}
```

Example joi validation for the dynamic keys:
```javascript
const joiObj = joi.object().keys({
  dynamicKeyHolder: joi
      .object()
      .pattern(/s/, joi.object().keys({
        id: joi
          .number()
          .description('Tbe ID for the reference')
          .example(123)
          .required(),
        name: joi
          .string()
          .allow('', null)
          .description('Name of something')
          .example('Jack')
          .required()
      }))
      .description('Some kind of list')
      .required()
```

I'm digging through your code and trying to decipher where it could be added and perhaps the "_setAlternativesProperties" function could be leveraged. But instead of using the `oneOf` property once it is converted to have `patternObj` so the distinction is clear 🤔 . Curious to hear your thoughts and if you have time to implement this feature? If not, maybe I can make a PR.

Also, maybe add the github link to the NPM repo :), should make it easier for other ppl to find this cool repo code. Thx again!

**Comment by kenspirit** [comment]
@PetarIvancevic I haven't used this feature in joi before.  I will try to take some time to check what structure it's generated d in each joi version.  Before that, I cannot tell where the new code could be.  But you can submit a PR anytime if you already figured out.

**Comment by kenspirit** [comment]
Enhanced by #11
