### ISSUE TITLE
Broke when use joi.forbidden()

### ISSUE THREAD

**Issue by FelipeBrizola** [kenspirit/joi-to-json#13]
When use joi.forbidden() the library throw an error, but in some scenarios this statement is helpful.
Adding x.forbidden all tests start to broke. Print below
![image](https://user-images.githubusercontent.com/5969512/120376430-4591f680-c2f2-11eb-8073-f9132e3df5c3.png)

Maybe should do a bypass in forbidden clause?

Thanks!

**Comment by kenspirit** [comment]
Hi @FelipeBrizola , I am sorry that the library should not break at any time if something unexpected is passed in.

I would like to know what is your scenario of using forbidden.  If you don't want extra fields to be passed, I think you can set options (allowUnknown) for joi to false.

**Comment by kenspirit** [comment]
Hi @FelipeBrizola, submitted a fix and release a patch to allow explicitly forbid fields as the example provided.

**Comment by FelipeBrizola** [comment]
Hi @kenspirit,
First of all, sorry for I send a feedback too late.
Your fix works fine right now and thanks for it.
I use allowUnknown, but the scenario that I used was something like that
```
.when(joi.object({ type: joi.string().equal(EnumInstallmentType.SKIP_PAYMENT).exist() }).unknown(), {
    then: joi.object({
        number: joi.forbidden(),
        number_skip_payment: joi.required()
    })
```

anyway, thanks a lot.
best regards
