### ISSUE TITLE
Ability to support custom format in JSON schema 

### ISSUE THREAD

**Issue by mo4islona** [kenspirit/joi-to-json#21]
Hi there!
First of all thanks for great job done so far.

The thing that is really missing — support for a `custom format`  and/or override format

https://json-schema.org/understanding-json-schema/reference/string.html#id7

```ts
Joi.object({
 prop: Joi.string().meta({ format: 'custom_format' })
})

// { prop: { type: 'string', format: 'custom_format' }} in json schema

Joi.object({
 prop: Joi.string().ip().meta({ format: 'custom_ip' })
})
// { prop: { type: 'string', format: 'custom_ip' }} 
//  not ipv4 in json schema
```

**Comment by kenspirit** [comment]
Enhancement is applied on version 2.2.0.  The final format of the field will be taken from meta and this would be the schema author's responsibility to ensure JSON schema parser can take this format.

**Comment by mo4islona** [comment]
Thanks!
