### ISSUE TITLE
Typescript supports

### ISSUE THREAD

**Issue by wirekang** [kenspirit/joi-to-json#31]
It would be great if this project has type definitions.

**Comment by kenspirit** [comment]
@wirekang There was a [PR](https://github.com/kenspirit/joi-to-json/pull/20) that is intended to do that.  I recommend to use joi type instead of just any.  Would you love to try to add it and send a PR?

**Comment by kenspirit** [comment]
Supported in 2.4.0

**Comment by wirekang** [comment]
Thank you!
