### ISSUE TITLE
Support readOnly and writeOnly properties in OpenAPI spec

### ISSUE THREAD

**Issue by jandppw** [kenspirit/joi-to-json#33]
Thanks for this glorious project. I am looking into this for a while, and am very happy with the results based on this package after 2 days.

I have a problem with marking properties as `readOnly` in OpenAPI specs. Is is this supported yet?

If not, after going through the code, I suggest adding it to `lib/parsers/open-api.js`, the same way you handle `depracated` (line 45), as a meta property.

**Comment by kenspirit** [comment]
Thanks for loving this tool and making such a great contribution!  Version 2.6.0 is released.
