### ISSUE TITLE
Add support for Joi key relationship options (`.or()`, `.xor()`, `.oxor()` `.and()`, & `.nand()`)

### ISSUE THREAD

**Issue by necropolina** [kenspirit/joi-to-json#38]
It looks like these Joi object schema options aren't supported at the moment, but they all should be implementable via:
- `oneOf` + `required` (for `xor` & `and`)
- `oneOf` (for `oxor` & `nand`)
-  `anyOf` (for `or`)

**Comment by kenspirit** [comment]
Yes, it's currently not supported yet.  Would you like to submit a PR?

**Comment by necropolina** [comment]
One potential part of the solution... rather than replicating the entire object schema, you could reference the object's keys using `required` and `not`. So for the above schema you could do:
```
{
  type: "object",
  oneOf: [
    { required: ["a"] },
    { required: ["b"] },
  ]
  properties: { a: { type: "string" }, b: { type: "number" } }
}
```

or, if it was a `xor`:
```
{
type: "object",
  oneOf: [
    { 
      required: ["a"], 
      not: { required: ["b"]}
    },
    { 
      required: ["b"] ,
      not: { required: ["a"]}
    }
  ],
  properties: { a: { type: "string" }, b: { type: "number" } }
}
```
Because `not: { required: [] }` results in "not allowed" rather than "not required.


so, for `oxor`:
```
{
type: "object",
  oneOf: [
    { 
      required: ["a"], 
      not: { required: ["b"]}
    },
    { 
      required: ["b"] ,
      not: { required: ["a"]}
    },
    { not: { required: ["a", "b"] } }
  ],
  properties: { a: { type: "string" }, b: { type: "number" } }
}
```

and `nand`:
```
{
type: "object",
  oneOf: [
    { not: { required: ["a", "b"] } }
    { not: { required: [] } }
  ],
  properties: { a: { type: "string" }, b: { type: "number" } }
}
```

**Comment by necropolina** [comment]
You're still effectively generating a schema object for each key, but much less than generating a bunch of full schema. `oneOf`/`anyOf` error messages aren't the most useful and don't really clue you into specific keys or schema either way.

It probably gets a bit more complicated tho when combining multiple key relationship constraints. I'll try to look into that a bit this week.

Not sure when I'll be able to dedicate some time to familiarizing myself with your package + joi's parser, but I'd be happy to check back here when I find a bit of time for it, if you or somebody else doesn't get to it first.

**Comment by kenspirit** [comment]
No hurry for implementation.  I think what we need to do is to come up the working JSON representation (As concise as possible and possibly different format for different JSON spec version).

For the `or` case, your proposal actually does not work as `oneOf` only valid WHEN ONLY ONE is matched.  But the joi `or` accepts both `a` and `b` exists scenario. (If you try https://www.jsonschemavalidator.net/, you can see that the `{ a:'1', b:2}`) failed for your schema but not the Joi definition.

Adding one option to your `xor` definition actually works for `or`:

```
{
  type: "object",
  oneOf: [
    { 
      required: [ "a" ], 
      not: { required: [ "b" ] }
    },
    { 
      required: [ "b" ] ,
      not: { required: [ "a" ] }
    },
    { 
      required: [ "a", "b" ]
    }
  ],
  properties: { a: { type: "string" }, b: { type: "number" } }
}
```

Your `oxor` does not work when validating against `{ a: '1' }` because it matches the first and third option.  I do not have idea on how to construct the json schema yet.

I think below is good enough for `nand`?

```
{
  type: "object",
  not: { required: [ "a", "b" ] },
  properties: { a: { type: "string" }, b: { type: "number" } }
}
```

**Comment by necropolina** [comment]
Ah good catch, I hadn't tested a couple of those lol.

The `oxor` one has been working for a schema I've been using tho, using json schema draft 7. `{ a: '1' }` shouldn't match the 3rd option as that option should result in "both a & b are individually forbidden".

And yeah, your `nand` should work. I hadn't tested wither you could have a `not: { required }` alongside a `oneOf` that contains other `not: { required }` options, but it's working for me. :)

**Comment by kenspirit** [comment]
> `{ a: '1' }` shouldn't match the 3rd option as that option should result in "both a & b are individually forbidden".

I think the 3rd option means "both a & b are not required at the same time"?

![image](https://user-images.githubusercontent.com/883277/193963177-d9599d89-8977-46c4-b3cf-3de19afe206a.png)

**Comment by necropolina** [comment]
Hmm, yeah the schema I wrote with that xor pattern fails in that schema validator with the same errors. Looks like vscode's schema validator just isn't throwing those errors. :P I would've thought `{ not: { required: [ "a", "b" ] } }` would only be satisfied if both keys are absent, but maybe not...

**Comment by kenspirit** [comment]
@necropolina, I have managed to write Joi and JSON schema for different cases.  Hopefully I have not missed any case.  `additionalProperties` should support either true or false.

```javascript
// At least one of a or b or c exists.
// Failed on { d: null }
const orJoi = joi.object({
  a: joi.string(),
  b: joi.number(),
  c: joi.boolean(),
  d: joi.any().valid(null)
}).or('a', 'b', 'c');

const orSchemaGeneral = {
  type: 'object',
  anyOf: [
    { required: ["a"] }, { required: ["b"] }, { required: ["c"] }
  ],
  properties: { a: { type: "string" }, b: { type: "number" }, c: { type: "boolean" }, d: { type: "null" } },
  additionalProperties: false
}


// Either a, b, and c All NOT exists, or all of them exists
// Failed on { a: 'hi', b: 1 }
const andJoi = joi.object({
  a: joi.string(),
  b: joi.number(),
  c: joi.boolean(),
  d: joi.any().valid(null)
}).and('a', 'b', 'c');

const andSchemaGeneral = {
  type: "object",
  oneOf: [
    {
      allOf: [
        {
          not: { required: ["a"] }
        },
        {
          not: { required: ["b"] }
        },
        {
          not: { required: ["c"] }
        }
      ]
    },
    { required: ["a", "b", "c"] }
  ],
  properties: { a: { type: "string" }, b: { type: "number" }, c: { type: "boolean" }, d: { type: "null" } },
  additionalProperties: false
};


// a, b, and c cannot all exist at the same time
// Failed on { a: 'hi', b: 1, c: true }
const nandJoi = joi.object({
  a: joi.string(),
  b: joi.number(),
  c: joi.boolean(),
  d: joi.any().valid(null)
}).nand('a', 'b', 'c');

const nandSchemaGeneral = {
  type: "object",
  not: { required: ["a", "b", "c"] },
  properties: { a: { type: "string" }, b: { type: "number" }, c: { type: "boolean" }, d: { type: "null" } },
  additionalProperties: false
};


// Only one of a, b and c can and must exist
// Failed on { d: null } or { a: 'hi', b: 1 }
const xorJoi = joi.object({
  a: joi.string(),
  b: joi.number(),
  c: joi.boolean(),
  d: joi.any().valid(null)
}).xor('a', 'b', 'c');

const xorSchemaDraft7 = {
  type: "object",
  if: { propertyNames: { enum: ["a", "b", "c"] }, minProperties: 2 },
  then: false,
  else: {
    oneOf: [
      {
        required: ["a"]
      },
      {
        required: ["b"]
      },
      {
        required: ["c"]
      }
    ]
  },
  properties: { a: { type: "string" }, b: { type: "number" }, c: { type: "boolean" }, d: { type: "null" } },
  additionalProperties: false
};

// Only one of a, b and c can exist
// Failed on { a: 'hi', b: 1 }
const oxorJoi = joi.object({
  a: joi.string(),
  b: joi.number(),
  c: joi.boolean(),
  d: joi.any().valid(null)
}).oxor('a', 'b', 'c');

const oxorSchemaGeneral = {
  type: "object",
  oneOf: [{ required: ["a"] }, { required: ["b"] }, { required: ["c"] }],
  properties: { a: { type: "string" }, b: { type: "number" }, c: { type: "boolean" }, d: { type: "null" } },
  additionalProperties: false
};
```

**Comment by kenspirit** [comment]
Version 3.0.0 after this [commit](https://github.com/kenspirit/joi-to-json/commit/8adf9de900f779d2e954e23292f7743fdc0a76ed) supports these relation operators.

**Comment by necropolina** [comment]
Awesome stuff, thanks so much for working on this!
