### ISSUE TITLE
Conversion of multiple `.shared()` produces invalid schema

### ISSUE THREAD

**Issue by ioder** [kenspirit/joi-to-json#51]
Using multiple calls to shared/link when defining schema produces invalid schema when it is passed to `parse` function. `joi` validation works fine.

```typescript
const schema1 = Joi.string().valid("Something-1").id("Something-1");
const schema2 = Joi.string().valid("Something-2").id("Something-2");

const schema3 = Joi.object({
    random: Joi.link("#Something-2"),
    random2: Joi.link("#Something-1"),
})
    .shared(schema1)
    .shared(schema2);

console.log(parse(schema3));
```
Result:
```JSON
{
    "type": "object",
    "properties": {
      "random": { "$ref": "#/$defs/Something-2" },
      "random2": { "$ref": "#/$defs/Something-1" }
    },
    "additionalProperties": false,
    "$defs": { "Something-1": { "const": "Something-1" } }
  }
```
As can be seen in the result, `$defs` object does not contain definition for `Something-2`.

Reproduction [link](https://codesandbox.io/p/devbox/joi-link-shared-reproduction-6pc9yc?file=%2Fsrc%2Findex.ts%3A10%2C29&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqxpvr1t00063b6hbuym3khq%2522%252C%2522sizes%2522%253A%255B59.49521458685313%252C40.50478541314687%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqxpvr1t00023b6h2jfmuxft%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqxpvr1t00033b6hdbtgdfjl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqxpvr1t00053b6hekx0b9o9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqxpvr1t00023b6h2jfmuxft%2522%253A%257B%2522id%2522%253A%2522clqxpvr1t00023b6h2jfmuxft%2522%252C%2522activeTabId%2522%253A%2522clqxq65y300023b6h4mn4vudp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxq65y300023b6h4mn4vudp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A29%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A29%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252Fts-node%252Fsrc%252Findex.ts%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1621%252C%2522endLineNumber%2522%253A1621%252C%2522startColumn%2522%253A12%252C%2522endColumn%2522%253A12%257D%255D%252C%2522id%2522%253A%2522clqxsusbp03sk3b6hqu4z1q4d%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clqxpvr1t00053b6hekx0b9o9%2522%253A%257B%2522id%2522%253A%2522clqxpvr1t00053b6hekx0b9o9%2522%252C%2522activeTabId%2522%253A%2522clqz33y9i05d73b6h4k7szhp3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clqz33y9i05d73b6h4k7szhp3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clqxpvr1t00033b6hdbtgdfjl%2522%253A%257B%2522id%2522%253A%2522clqxpvr1t00033b6hdbtgdfjl%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clqxsvlfp004u3b6ha8bjbr6n%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqxsvlfp004u3b6ha8bjbr6n%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by kenspirit** [comment]
Thanks for reporting this issue.  It's fixed in version 4.2.1 already.
